{
 "title": "JMeter Benchmark Dashboard",
 "tags": [
  "jmeter",
  "performance",
  "REST"
 ],
 "panels": [
  {
   "title": "Temps moyen (avg)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 8 },
   "targets": [
    {
     "query": "from(bucket:\"jmeter\") |> range(start:-1h) |> filter(fn:(r) => r._measurement==\"jmeter\" and r._field==\"avg\" and r.threadGroup==\"READ-heavy\") |> aggregateWindow(every:10s, fn:mean)"
    },
    {
     "query": "from(bucket:\"jmeter\") |> range(start:-1h) |> filter(fn:(r) => r._measurement==\"jmeter\" and r._field==\"avg\" and r.threadGroup==\"JOIN-filter\") |> aggregateWindow(every:10s, fn:mean)"
    },
    {
     "query": "from(bucket:\"jmeter\") |> range(start:-1h) |> filter(fn:(r) => r._measurement==\"jmeter\" and r._field==\"avg\" and r.threadGroup==\"MIXED\") |> aggregateWindow(every:10s, fn:mean)"
    },
    {
     "query": "from(bucket:\"jmeter\") |> range(start:-1h) |> filter(fn:(r) => r._measurement==\"jmeter\" and r._field==\"avg\" and r.threadGroup==\"HEAVY-body\") |> aggregateWindow(every:10s, fn:mean)"
    }
   ]
  },
  {
   "title": "Temps min / max",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 8 },
   "targets": [
    {
     "query": "from(bucket:\"jmeter\") |> range(start:-1h) |> filter(fn:(r)=>r._measurement==\"jmeter\" and r._field==\"min\" and r.threadGroup==\"READ-heavy\") |> aggregateWindow(every:10s, fn:mean)"
    },
    {
     "query": "from(bucket:\"jmeter\") |> range(start:-1h) |> filter(fn:(r)=>r._measurement==\"jmeter\" and r._field==\"max\" and r.threadGroup==\"READ-heavy\") |> aggregateWindow(every:10s, fn:mean)"
    },
    {
     "query": "from(bucket:\"jmeter\") |> range(start:-1h) |> filter(fn:(r)=>r._measurement==\"jmeter\" and r._field==\"min\" and r.threadGroup==\"JOIN-filter\") |> aggregateWindow(every:10s, fn:mean)"
    },
    {
     "query": "from(bucket:\"jmeter\") |> range(start:-1h) |> filter(fn:(r)=>r._measurement==\"jmeter\" and r._field==\"max\" and r.threadGroup==\"JOIN-filter\") |> aggregateWindow(every:10s, fn:mean)"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 24, "h": 8 },
   "targets": [
    {
     "query": "from(bucket:\"jmeter\") |> range(start:-1h) |> filter(fn:(r)=> r._measurement==\"jmeter\" and r._field==\"throughput\" and r.threadGroup==\"READ-heavy\") |> aggregateWindow(every:10s, fn:mean)"
    },
    {
     "query": "from(bucket:\"jmeter\") |> range(start:-1h) |> filter(fn:(r)=> r._measurement==\"jmeter\" and r._field==\"throughput\" and r.threadGroup==\"JOIN-filter\") |> aggregateWindow(every:10s, fn:mean)"
    },
    {
     "query": "from(bucket:\"jmeter\") |> range(start:-1h) |> filter(fn:(r)=> r._measurement==\"jmeter\" and r._field==\"throughput\" and r.threadGroup==\"MIXED\") |> aggregateWindow(every:10s, fn:mean)"
    },
    {
     "query": "from(bucket:\"jmeter\") |> range(start:-1h) |> filter(fn:(r)=> r._measurement==\"jmeter\" and r._field==\"throughput\" and r.threadGroup==\"HEAVY-body\") |> aggregateWindow(every:10s, fn:mean)"
    }
   ]
  },
  {
   "title": "Taux d'erreur (%)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 24, "w": 24, "h": 8 },
   "targets": [
    {
     "query": "from(bucket:\"jmeter\") |> range(start:-1h) |> filter(fn:(r)=> r._measurement==\"jmeter\" and r._field==\"error%\" and r.threadGroup==\"READ-heavy\") |> aggregateWindow(every:10s, fn:mean)"
    },
    {
     "query": "from(bucket:\"jmeter\") |> range(start:-1h) |> filter(fn:(r)=> r._measurement==\"jmeter\" and r._field==\"error%\" and r.threadGroup==\"JOIN-filter\") |> aggregateWindow(every:10s, fn:mean)"
    },
    {
     "query": "from(bucket:\"jmeter\") |> range(start:-1h) |> filter(fn:(r)=> r._measurement==\"jmeter\" and r._field==\"error%\" and r.threadGroup==\"MIXED\") |> aggregateWindow(every:10s, fn:mean)"
    },
    {
     "query": "from(bucket:\"jmeter\") |> range(start:-1h) |> filter(fn:(r)=> r._measurement==\"jmeter\" and r._field==\"error%\" and r.threadGroup==\"HEAVY-body\") |> aggregateWindow(every:10s, fn:mean)"
    }
   ]
  }
 ]
}